packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.4'
  - '@turbo/darwin-arm64@2.11.4'
  - '@turbo/linux-64@2.11.4'
  - '@turbo/linux-arm64@2.11.4'
  - '@turbo/windows-64@2.11.4'
  - '@turbo/windows-arm64@2.11.4'
  - '@vitest/mocker@5.0.2'
  - '@vitest/spy@5.0.2'
  - turbo@2.11.4
  - vitest@5.0.2
  - '@scalar/client-side-rendering@0.4.5'
  - '@scalar/helpers@0.15.0'
  - '@scalar/hono-api-reference@0.12.6'
  - '@scalar/schemas@0.12.1'
  - '@scalar/types@0.22.1'
  - '@better-auth/core@1.7.6'
  - '@better-auth/drizzle-adapter@1.7.6'
  - '@better-auth/kysely-adapter@1.7.6'
  - '@better-auth/memory-adapter@1.7.6'
  - '@better-auth/mongo-adapter@1.7.6'
  - '@better-auth/prisma-adapter@1.7.6'
  - '@better-auth/telemetry@1.7.6'
  - better-auth@1.7.6
  - resend@6.29.0
  - '@aws-sdk/client-s3@3.1141.0'

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - sharp
