/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and DB-connectivity check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "error";
                            /** @enum {string} */
                            database: "ok" | "unreachable";
                        };
                    };
                };
                /** @description Database unreachable */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "error";
                            /** @enum {string} */
                            database: "ok" | "unreachable";
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** API name and version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            version: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/handle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        handle: string;
                    };
                };
            };
            responses: {
                /** @description Handle updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            handle: string;
                        };
                    };
                };
                /** @description Handle taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Still within the 30-day cooldown */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        trace?: never;
    };
    "/v1/me/affiliations/verify/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        institutionEmail: string;
                    };
                };
            };
            responses: {
                /** @description OTP sent */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/affiliations/verify/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        code: string;
                        department: string;
                        /** @enum {string} */
                        position: "undergrad" | "masters" | "phd" | "postdoc" | "faculty" | "staff" | "industry" | "other";
                    };
                };
            };
            responses: {
                /** @description Affiliation recorded */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            institutionName: string;
                            department: string;
                            /** @enum {string} */
                            position: "undergrad" | "masters" | "phd" | "postdoc" | "faculty" | "staff" | "industry" | "other";
                            expiresAt: string | null;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Export emailed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Account soft-deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/works/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve any arXiv ID/URL or DOI to a work, ingesting it on first sight */
        get: {
            parameters: {
                query: {
                    /** @description An arXiv ID/URL, DOI, or PMID/PubMed URL. */
                    id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved to an existing or newly ingested work */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "found" | "ingested" | "pending";
                            /** Format: uuid */
                            workId?: string;
                        };
                    };
                };
                /** @description Ingestion is still in progress — retry shortly */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "found" | "ingested" | "pending";
                            /** Format: uuid */
                            workId?: string;
                        };
                    };
                };
                /** @description id isn't a recognizable arXiv ID/URL, DOI, or PMID */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description No connector could find a record for this identifier */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/works/{workId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a work's metadata (title, abstract, authors, identifiers, latest version) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The work */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            title: string;
                            abstract: string | null;
                            workType: string;
                            publishedAt: string | null;
                            authors: {
                                name: string;
                                /** Format: uuid */
                                personId: string;
                            }[];
                            identifiers: {
                                scheme: string;
                                valueNormalized: string;
                            }[];
                            latestVersion: {
                                versionLabel: string;
                                license: string | null;
                                canDisplayFullText: boolean;
                                pdfUrl: string | null;
                                htmlUrl: string | null;
                                sourceUrl: string | null;
                            } | null;
                        };
                    };
                };
                /** @description No work with this id */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/works/{workId}/reader": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the sanitized reader document for a work's latest version */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The reader document is ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ready" | "pending";
                            bodyHtml?: string;
                            outline?: unknown[];
                            figures?: unknown[];
                            references?: unknown[];
                        };
                    };
                };
                /** @description The reader document is still being built — retry shortly */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ready" | "pending";
                            bodyHtml?: string;
                            outline?: unknown[];
                            figures?: unknown[];
                            references?: unknown[];
                        };
                    };
                };
                /** @description The work has no version this pipeline can build a reader document for */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/works/{workId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Notes for this work, ordered helpful → needs more ratings → not helpful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                workId: string;
                                /** Format: uuid */
                                workVersionId: string | null;
                                /** Format: uuid */
                                authorUserId: string;
                                type: string;
                                body: string;
                                anchor?: unknown;
                                status: string;
                                createdAt: string;
                                ratingCounts: {
                                    helpful: number;
                                    somewhat: number;
                                    not_helpful: number;
                                };
                                evidence: {
                                    kind: string;
                                    url: string | null;
                                    label: string | null;
                                }[];
                                authorReply: {
                                    body: string;
                                    addressedInVersion: string | null;
                                } | null;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    workId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        workId: string;
                        /** Format: uuid */
                        workVersionId?: string | null;
                        /** @enum {string} */
                        type: "reproduced" | "failed_to_reproduce" | "correction" | "missing_context" | "code_data_issue" | "helpful_resource";
                        body: string;
                        anchor?: string | number | boolean | null | {
                            [key: string]: unknown;
                        } | unknown[];
                        language?: string | null;
                        evidence: {
                            /** @enum {string} */
                            kind: "repository" | "log_output" | "dataset" | "citation" | "publication" | "external_link" | "upload" | "other";
                            url?: string | null;
                            /** Format: uuid */
                            workId?: string | null;
                            storageKey?: string | null;
                            label?: string | null;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Note created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                            /** Format: uuid */
                            workId: string;
                            /** Format: uuid */
                            workVersionId: string | null;
                            /** Format: uuid */
                            authorUserId: string;
                            type: string;
                            body: string;
                            anchor?: unknown;
                            status: string;
                            createdAt: string;
                            ratingCounts: {
                                helpful: number;
                                somewhat: number;
                                not_helpful: number;
                            };
                            evidence: {
                                kind: string;
                                url: string | null;
                                label: string | null;
                            }[];
                            authorReply: {
                                body: string;
                                addressedInVersion: string | null;
                            } | null;
                        };
                    };
                };
                /** @description Invalid note */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Not eligible to write a note yet */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/{noteId}/ratings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        value: "helpful" | "somewhat" | "not_helpful";
                        reasons?: string[];
                    };
                };
            };
            responses: {
                /** @description Rating recorded (created or updated) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: string;
                        };
                    };
                };
                /** @description Not eligible to rate */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description No such note */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notes/{noteId}/replies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    noteId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        body: string;
                        addressedInVersion?: string | null;
                    };
                };
            };
            responses: {
                /** @description Reply created or updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            body: string;
                        };
                    };
                };
                /** @description No approved author claim on this work */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description No such note */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        targetType: "note" | "user" | "profile";
                        /** Format: uuid */
                        targetId: string;
                        reason: string;
                        details?: string;
                    };
                };
            };
            responses: {
                /** @description Report filed */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{userId}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Blocked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Can't block yourself */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Unblocked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
